---
- name: Setup ELK with Docker
  hosts: elk
  become: true
  remote_user: azadmin
  tasks:
   - name: Update apt
     apt: 
       update_cache: yes
       force_apt_get: yes
   - name: Install docker.io
     apt:
       name: docker.io  
   - name: Install python3-pip
     apt:
       name: python3-pip
   - name: Docker install using pip
     pip:
       name: docker 
   - name: Set vm max map count
     sysctl:
       name: vm.max_map_count
       value: '262144' 
       state: present
       reload: yes
   - name: Setup container sebp/elk
     docker_container:
       name: elk
       image: sebp/elk:761
       state: started
       restart_policy: always
       published_ports:
         - 5601:5601
         - 9200:9200
         - 5044:5044
   - name: Enable docker service on boot
     systemd:
       name: docker
       enabled: yes   

